import 'dotenv/config';
import { db } from './src/prisma/db.js';

async function simulate() {
  console.log("🏙️ Starting CityConnect User Simulation...");

  try {
    // 1. Person Creation (V1 Identity Model)
    console.log("\n[1/5] Simulating User Onboarding...");
    const email = "simulated.user@cityconnect.local";
    let person;
    const existingId = await db.orm.public.PersonIdentifier.where({ type: 'EMAIL', normalizedValue: email.toLowerCase() }).all().first();
    if (existingId) {
        person = await db.orm.public.Person.where({ id: existingId.personId }).all().first();
        console.log(`✅ Found existing simulated person: ${person?.firstName}`);
    } else {
        person = await db.orm.public.Person.create({ firstName: 'Simulated', lastName: 'Tester' });
        await db.orm.public.PersonIdentifier.create({ personId: person!.id, type: 'EMAIL', normalizedValue: email.toLowerCase() });
        console.log(`✅ Created new person: ${person?.firstName} (${email})`);
    }

    // Initialize Wallet
    let wallet = await db.orm.public.Wallet.where({ personId: person!.id }).all().first();
    if (!wallet) {
        wallet = await db.orm.public.Wallet.create({
            personId: person!.id,
            balance: 0,
            currency: 'USD',
        });
        console.log(`✅ Initialized CityWallet for person. Balance: ${wallet.balance}`);
    } else {
        console.log(`✅ CityWallet already exists. Balance: ${wallet.balance}`);
    }

    // 2. Publisher Setup (Need something to interact with)
    console.log("\n[2/5] Setting up News Publisher & Post...");
    let org = await db.orm.public.Organization.where({ type: 'PUBLISHER' }).all().first();
    if (!org) {
        org = await db.orm.public.Organization.create({
            name: "City News Daily",
            type: "PUBLISHER",
            address: "Downtown"
        });
        console.log(`✅ Created Publisher: ${org.name}`);
    }

    // Create a Post
    const post = await db.orm.public.Post.create({
        organizationId: org.id,
        title: "Test Simulation Post",
        content: "This is a post generated by the simulation script to test social interactions.",
        category: "NEWS",
        status: "PUBLISHED",
        isEmergency: false,
        shareCount: 0
    });
    console.log(`✅ Published Post: "${post.title}"`);

    // 3. Social Interaction: Liking
    console.log("\n[3/5] Simulating User Liking Post...");
    const like = await db.orm.public.PostLike.create({
        postId: post.id,
        personId: person!.id
    });
    console.log(`✅ User successfully liked the post. Like ID: ${like.id}`);

    // 4. Social Interaction: Commenting
    console.log("\n[4/5] Simulating User Commenting...");
    const comment = await db.orm.public.Comment.create({
        postId: post.id,
        personId: person!.id,
        content: "Wow, CityConnect is working flawlessly! Excited for the launch."
    });
    console.log(`✅ User successfully commented: "${comment.content}"`);

    // 5. Social Interaction: Sharing
    console.log("\n[5/5] Simulating User Sharing...");
    await db.orm.public.Post.where({ id: post.id }).update({
        shareCount: (post.shareCount || 0) + 1
    });
    console.log(`✅ User shared the post.`);

    // Cleanup (optional, but good practice for repeatable tests)
    console.log("\n🧹 Cleaning up simulation data...");
    await db.orm.public.Comment.where({ id: comment.id }).delete();
    await db.orm.public.PostLike.where({ id: like.id }).delete();
    await db.orm.public.Post.where({ id: post.id }).delete();
    // We leave the user and wallet for future tests

    console.log("\n🎉 Simulation complete! All core social and identity systems are functional.");

  } catch (error) {
    console.error("\n❌ Simulation Failed:", error);
  }
}

simulate();
