export const POPULAR_UOMS = [
  "KG", "GRAMS", "POUNDS (LB)", "OUNCES (OZ)", 
  "LITERS", "MILLILITERS (ML)", "GALLONS", "FLUID OUNCES (FL OZ)",
  "PIECES", "EACH (EA)", "UNITS", "PORTIONS", "SLICES", "PLATES",
  "PACKS", "BAGS", "BOXES", "CARTONS", "CASES", "BOTTLES", "CANS", 
  "BUNCHES", "LOAVES", "DOZEN", "TINS", "JARS", "TUBS", "TRAYS"
];
