export interface NormalizedWebhookEvent {
  /** The unique event ID generated by the provider, used for exactly-once processing (PaymentEvent.providerEventId) */
  providerEventId: string;
  /** The provider's transaction ID (Payment.providerReference) */
  providerReference: string;
  /** CityOS internal payment reference (Payment.reference) */
  reference: string | null;
  /** Normalized status */
  status: 'SUCCESS' | 'FAILED' | 'PENDING' | 'REFUNDED';
  /** Total amount reported by the provider in the event */
  amount: number;
  /** Currency reported by the provider */
  currency: string;
  /** Raw webhook payload (excluding sensitive credentials like PANs/CVVs if any were present) */
  rawPayload: any;
}

export interface InitializePaymentInput {
  amount: number;
  currency: string;
  /** CityOS internal payment reference (Payment.reference) */
  reference: string;
  /** The customer's email address */
  email: string;
  metadata?: Record<string, any>;
  callbackUrl: string;
}

export interface InitializePaymentOutput {
  success: boolean;
  authorizationUrl?: string;
  isSandbox?: boolean;
  providerReference?: string;
  error?: string;
}

export interface VerifyPaymentOutput {
  success: boolean;
  status: 'SUCCESS' | 'FAILED' | 'PENDING';
  amount?: number;
  currency?: string;
  error?: string;
}

export interface RefundPaymentInput {
  providerReference: string;
  amount?: number;
  reason?: string;
}

export interface RefundPaymentOutput {
  success: boolean;
  status: 'REFUNDED' | 'FAILED' | 'PENDING';
  providerRefundId?: string;
  error?: string;
}

export interface PaymentProviderAdapter {
  /** The internal name of the provider (e.g., 'PAYSTACK', 'FLUTTERWAVE') */
  readonly providerName: string;

  /** Initialize a new payment session with the provider */
  initializePayment(input: InitializePaymentInput): Promise<InitializePaymentOutput>;

  /** Verify a payment status directly with the provider API */
  verifyPayment(reference: string): Promise<VerifyPaymentOutput>;

  /** Verify the HMAC/cryptographic signature of an incoming webhook payload */
  validateWebhookSignature(rawBody: string, signature: string | null): boolean;

  /** Normalize the provider's specific webhook format into a strictly typed CityOS event */
  normalizeWebhookEvent(payload: any): NormalizedWebhookEvent | null;

  /** Issue a refund via the provider API */
  refundPayment(input: RefundPaymentInput): Promise<RefundPaymentOutput>;
}
